CREATE PROC UPDATE_HOPDONG
	@MADOITAC CHAR(12),
	@MATHUE CHAR(12),
	@DATE date,
	@HOAHONG FLOAT
AS
BEGIN
	BEGIN TRAN
		IF NOT EXISTS (SELECT * FROM DOITAC WHERE DOITAC.MADOITAC = @MADOITAC)
		BEGIN
			ROLLBACK
			RAISERROR(N'Đối tác không tồn tại', 16, 1)
		END
		WAITFOR DELAY '00:00:05'
		UPDATE dbo.HOPDONG
		SET TGHIEULUC = @DATE, PHANTRAMHOAHONG = @HOAHONG
		WHERE MADOITAC = @MADOITAC AND MATHUE = @MATHUE

	COMMIT TRAN
END
GO

EXEC dbo.UPDATE_HOPDONG @MADOITAC = 'DT0000000001',       -- char(12)
                        @MATHUE = 'MT0000000001',         -- char(12)
                        @DATE = '2021-11-20', -- date
                        @HOAHONG = 4        -- float