CREATE PROC XEMHDCU
	@MADT CHAR(12)
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRAN
		IF NOT EXISTS (SELECT * FROM DOITAC WHERE DOITAC.MADOITAC = @MADT)
		BEGIN
			ROLLBACK
			RAISERROR(N'Đối tác không tồn tại', 16, 1)
		END
		SELECT *
		FROM dbo.HOPDONG
		WHERE MADOITAC = @MADT AND TGHIEULUC < GETDATE()
	COMMIT TRAN
END
GO

SELECT* FROM dbo.HOPDONG

EXEC dbo.XEMHDCU @MADT = 'DT0000000001' -- char(12)

DROP PROC XEMHDCU