use DATH1
GO

CREATE PROC XEMTONKHO
	@MADT CHAR(12)
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRAN
	IF NOT EXISTS (SELECT * FROM dbo.DOITAC WHERE MADOITAC = @MADT)
	BEGIN
		ROLLBACK
		RAISERROR(N'Không tồn tại đối tác',16,1)
	END
	SELECT dbo.QUANLYKHO.* FROM dbo.SANPHAM, dbo.QUANLYKHO WHERE dbo.QUANLYKHO.MADOITAC = @MADT AND dbo.SANPHAM.MASP = dbo.QUANLYKHO.MASP
	COMMIT TRAN
END
GO

EXEC dbo.XEMTONKHO @MADT = 'DT0000000001' -- char(12)