USE DATH1

BEGIN TRANSACTION
SET TRAN ISOLATION LEVEL Serializable
SELECT *
FROM dbo.HOPDONG
WHERE TGHIEULUC > GETDATE()


WAITFOR DELAY '00:00:05'

SELECT *
FROM dbo.HOPDONG
WHERE TGHIEULUC > GETDATE()
COMMIT TRANSACTION